sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HFJsnzWN1XGiaJfM8ctJESHbXmpcW6gdn1LfMem/70JBTWhym2At7ZQrsykKCDLk8vylZfDOA3Vk7I9QROtnatBcb2WyoHtD/BK2vSwl79bhLySA6bkTKonpQGXqy4ZIq77QaNke6RYV8CWgjoRnhIhcukdI3QfC85xiuHOUu7QYskcIopyeTjb4QRuibu1g/+2KN47FgTMBAER+Kbtt4CGb3NmUw1T+7FoYUdY3L3DREi2yGbnA1yv/AAWpHnNcr6EoVCWojYsh/wgXKowsrXsg4DZHCAJMq62x2Hdm4TMRvZmaCkDib+JcX8X8C7jJqT5c/eLk2j4buZlDEQP2RKtu4iv9G3a53WpKxwVxD9K5s/7XQoXAveHgXYHNhucVLKmR/ieiCU/TmEIoXOAmkzX4YbwIXtwQMLe452Pimm1kpD6w75Y7m7URgQJrZmsB3KzoW/aPLxQRI8x1W61W+wjI5qEhf7C5IjKfa696mEdrEVpe3LDGFwRipG6yLzIEGRsFa1R/0atw0LtCQF8z5hi01arslYTVyztUivBP7pSdjCwINjzmwyA+CefyRESU7z1VQ0NYNTDwBKlpOUwHhkQDPpiwNzrInSZKskHsOftDHiclkt22U3RWfBgZglP33tQEYqUlGSlnZnRkJyBK9ITi1dHBRwzET3cYfn9z7g8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Immortals--Masterpieces-of-Fiction-Crowned-by-the-French-Academy---Complete_4000
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy